import type { CategoryMeta, CategoryGroup } from '../types/categories';

export const CATEGORIES: CategoryMeta[] = [
  // Empire Design (11)
  { category: 'governments', group: 'empire', displayName: { en: 'Governments', it: 'Governi' }, icon: '🏛️' },
  { category: 'authorities', group: 'empire', displayName: { en: 'Authorities', it: 'Autorità' }, icon: '👑' },
  { category: 'civics', group: 'empire', displayName: { en: 'Civics', it: 'Civiche' }, icon: '📜' },
  { category: 'origins', group: 'empire', displayName: { en: 'Origins', it: 'Origini' }, icon: '🌟' },
  { category: 'ethics', group: 'empire', displayName: { en: 'Ethics', it: 'Etiche' }, icon: '⚖️' },
  { category: 'species_classes', group: 'empire', displayName: { en: 'Species Classes', it: 'Classi Specie' }, icon: '🧬' },
  { category: 'traits', group: 'empire', displayName: { en: 'Traits', it: 'Tratti' }, icon: '🧠' },
  { category: 'species_rights', group: 'empire', displayName: { en: 'Species Rights', it: 'Diritti Specie' }, icon: '✊' },
  { category: 'personalities', group: 'empire', displayName: { en: 'AI Personalities', it: 'Personalità AI' }, icon: '🤖' },
  { category: 'name_lists', group: 'empire', displayName: { en: 'Name Lists', it: 'Liste Nomi' }, icon: '📋' },
  { category: 'prescripted_countries', group: 'empire', displayName: { en: 'Prescripted Countries', it: 'Paesi Prescritti' }, icon: '🏴' },
  // Economy & Planets (10)
  { category: 'buildings', group: 'economy', displayName: { en: 'Buildings', it: 'Edifici' }, icon: '🏗️' },
  { category: 'districts', group: 'economy', displayName: { en: 'Districts', it: 'Distretti' }, icon: '🏘️' },
  { category: 'pop_jobs', group: 'economy', displayName: { en: 'Pop Jobs', it: 'Lavori Pop' }, icon: '👷' },
  { category: 'planet_classes', group: 'economy', displayName: { en: 'Planet Classes', it: 'Classi Pianeta' }, icon: '🌍' },
  { category: 'deposits', group: 'economy', displayName: { en: 'Deposits', it: 'Giacimenti' }, icon: '💎' },
  { category: 'decisions', group: 'economy', displayName: { en: 'Decisions', it: 'Decisioni' }, icon: '📝' },
  { category: 'pop_categories', group: 'economy', displayName: { en: 'Pop Categories', it: 'Categorie Pop' }, icon: '👥' },
  { category: 'economic_categories', group: 'economy', displayName: { en: 'Economic Categories', it: 'Categorie Economiche' }, icon: '💰' },
  { category: 'trade_conversions', group: 'economy', displayName: { en: 'Trade Conversions', it: 'Conversioni Commerciali' }, icon: '🔄' },
  { category: 'terraform', group: 'economy', displayName: { en: 'Terraform', it: 'Terraformazione' }, icon: '🌱' },
  // Tech & Traditions (6)
  { category: 'technologies', group: 'tech', displayName: { en: 'Technologies', it: 'Tecnologie' }, icon: '🔬' },
  { category: 'traditions', group: 'tech', displayName: { en: 'Traditions', it: 'Tradizioni' }, icon: '📿' },
  { category: 'ascension_perks', group: 'tech', displayName: { en: 'Ascension Perks', it: 'Perk Ascensione' }, icon: '⬆️' },
  { category: 'edicts', group: 'tech', displayName: { en: 'Edicts', it: 'Editti' }, icon: '📢' },
  { category: 'policies', group: 'tech', displayName: { en: 'Policies', it: 'Politiche' }, icon: '📰' },
  { category: 'agendas', group: 'tech', displayName: { en: 'Agendas', it: 'Agende' }, icon: '📅' },
  // Military (9)
  { category: 'ship_sizes', group: 'military', displayName: { en: 'Ship Sizes', it: 'Dimensioni Navi' }, icon: '🚀' },
  { category: 'component_templates', group: 'military', displayName: { en: 'Component Templates', it: 'Template Componenti' }, icon: '⚙️' },
  { category: 'section_templates', group: 'military', displayName: { en: 'Section Templates', it: 'Template Sezioni' }, icon: '🔧' },
  { category: 'armies', group: 'military', displayName: { en: 'Armies', it: 'Eserciti' }, icon: '⚔️' },
  { category: 'war_goals', group: 'military', displayName: { en: 'War Goals', it: 'Obiettivi di Guerra' }, icon: '🎯' },
  { category: 'casus_belli', group: 'military', displayName: { en: 'Casus Belli', it: 'Casus Belli' }, icon: '🏳️' },
  { category: 'bombardment_stances', group: 'military', displayName: { en: 'Bombardment Stances', it: 'Posizioni Bombardamento' }, icon: '💥' },
  { category: 'ship_behaviors', group: 'military', displayName: { en: 'Ship Behaviors', it: 'Comportamenti Nave' }, icon: '🎮' },
  { category: 'global_ship_designs', group: 'military', displayName: { en: 'Ship Designs', it: 'Design Navi' }, icon: '✏️' },
  // Exploration & Events (9)
  { category: 'events', group: 'exploration', displayName: { en: 'Events', it: 'Eventi' }, icon: '📖' },
  { category: 'anomalies', group: 'exploration', displayName: { en: 'Anomalies', it: 'Anomalie' }, icon: '❓' },
  { category: 'archaeological_sites', group: 'exploration', displayName: { en: 'Archaeological Sites', it: 'Siti Archeologici' }, icon: '🏺' },
  { category: 'relics', group: 'exploration', displayName: { en: 'Relics', it: 'Reliquie' }, icon: '🏆' },
  { category: 'on_actions', group: 'exploration', displayName: { en: 'On Actions', it: 'On Actions' }, icon: '⚡' },
  { category: 'solar_system_initializers', group: 'exploration', displayName: { en: 'System Initializers', it: 'Inizializzatori Sistemi' }, icon: '☀️' },
  { category: 'star_classes', group: 'exploration', displayName: { en: 'Star Classes', it: 'Classi Stella' }, icon: '⭐' },
  { category: 'ambient_objects', group: 'exploration', displayName: { en: 'Ambient Objects', it: 'Oggetti Ambiente' }, icon: '🌌' },
  { category: 'leader_classes', group: 'exploration', displayName: { en: 'Leader Classes', it: 'Classi Leader' }, icon: '👤' },
  // Scripting (9)
  { category: 'scripted_effects', group: 'scripting', displayName: { en: 'Scripted Effects', it: 'Effetti Script' }, icon: '⚡' },
  { category: 'scripted_triggers', group: 'scripting', displayName: { en: 'Scripted Triggers', it: 'Trigger Script' }, icon: '🎯' },
  { category: 'scripted_modifiers', group: 'scripting', displayName: { en: 'Scripted Modifiers', it: 'Modificatori Script' }, icon: '🔢' },
  { category: 'scripted_variables', group: 'scripting', displayName: { en: 'Scripted Variables', it: 'Variabili Script' }, icon: '📊' },
  { category: 'script_values', group: 'scripting', displayName: { en: 'Script Values', it: 'Valori Script' }, icon: '🔣' },
  { category: 'inline_scripts', group: 'scripting', displayName: { en: 'Inline Scripts', it: 'Script Inline' }, icon: '📄' },
  { category: 'defines', group: 'scripting', displayName: { en: 'Defines', it: 'Definizioni' }, icon: '🔧' },
  { category: 'static_modifiers', group: 'scripting', displayName: { en: 'Static Modifiers', it: 'Modificatori Statici' }, icon: '📌' },
  { category: 'random_names', group: 'scripting', displayName: { en: 'Random Names', it: 'Nomi Casuali' }, icon: '🎲' },
  // Graphics & UI (7)
  { category: 'icons', group: 'graphics', displayName: { en: 'Icons', it: 'Icone' }, icon: '🖼️' },
  { category: 'event_pictures', group: 'graphics', displayName: { en: 'Event Pictures', it: 'Immagini Evento' }, icon: '🎨' },
  { category: 'empire_flags', group: 'graphics', displayName: { en: 'Empire Flags', it: 'Bandiere Impero' }, icon: '🚩' },
  { category: 'loading_screens', group: 'graphics', displayName: { en: 'Loading Screens', it: 'Schermate Caricamento' }, icon: '🖥️' },
  { category: 'gui_files', group: 'graphics', displayName: { en: 'GUI Files', it: 'File GUI' }, icon: '🪟' },
  { category: 'sprite_libraries', group: 'graphics', displayName: { en: 'Sprite Libraries', it: 'Librerie Sprite' }, icon: '🎭' },
  { category: 'music_sound', group: 'graphics', displayName: { en: 'Music & Sound', it: 'Musica e Suoni' }, icon: '🎵' },
];

export const CATEGORY_GROUPS: { group: CategoryGroup; label: { en: string; it: string } }[] = [
  { group: 'empire', label: { en: 'Empire Design', it: 'Progettazione Impero' } },
  { group: 'economy', label: { en: 'Economy & Planets', it: 'Economia e Pianeti' } },
  { group: 'tech', label: { en: 'Tech & Traditions', it: 'Tech e Tradizioni' } },
  { group: 'military', label: { en: 'Military', it: 'Militare' } },
  { group: 'exploration', label: { en: 'Exploration & Events', it: 'Esplorazione e Eventi' } },
  { group: 'scripting', label: { en: 'Scripting', it: 'Scripting' } },
  { group: 'graphics', label: { en: 'Graphics & UI', it: 'Grafica e UI' } },
  { group: 'localisation', label: { en: 'Localisation', it: 'Localizzazione' } },
];
